---
- name: Extra vars vault
  connection: local
  hosts: localhost
  gather_facts: no

  # reference the encrypted variable file
  vars_files:
    - vars/oscreds.yml

  tasks:
    - name: print out encrypted vars
      no_log: true
      ansible.builtin.debug:
        msg: "{{ imscloud }}"

