---
- name: Challenge 03 #- This solution requires no modification of the existing templates. Instead, we leverage the usage of variable precedence
  hosts: fry
  connection: ansible.builtin.ssh
  gather_facts: no
  vars:
          planet: "{{ item.planet }}"
  tasks:
    - name: challenge task
      ansible.builtin.template:
        src: templates/mission-orders.txt.j2     # name of the template on ansible controller
        dest: "~/{{ item.mission }}-mission-orders.txt"  # each time through the loop, we want a file named uniquely
      loop:   # each time through the loop, each dict (list entry) will be an "item"
          - {"mission": "primary", "planet": "luna park"}
          - {"mission": "secondary", "planet": "cineplex 14"}  ## This is the list we want to loop across

